name: simple_invoice_generator
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.2.2
  pdf: 3.10.6
  zxing_lib: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Asap
      fonts:
        - asset: assets/fonts/Asap-VariableFont_wdth,wght.ttf
